name: Update README with Last.fm Scrobbles

on:
  schedule:
    - cron: '0 * * * *'  
  workflow_dispatch: 

jobs:
  update-readme:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.x

      - name: Install Requirements
        run: pip install requests

      - name: Update README
        env:
          LASTFM_API_KEY: ${{ secrets.LASTFM_API_KEY }} 
        run: python update_readme.py

      - name: Commit and Push Changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git pull origin main || true
          git add README.md
          git commit -m "Update README with Last.fm Scrobbles" || true
          git push origin main
